### PR TITLE
Only activate on Mustache files

### LINKED ISSUE #6: Overenthusistic
When I have this package enabled and try to use handlebar packages this package gets used first for `file.hbs` signatures.

### PR DESCRIPTION
**Pull request by silvenon**
Fixes #6.

### CODE REVIEW

**Comment by dasilvacontin** [comment]
:+1:

**Comment by dasilvacontin** [comment]
PR #5 added support for `hjs`.

**Comment by silvenon** [comment]
Added `hjs` back.

**Comment by dasilvacontin** [comment]
:+1:

**Comment by kevinsawicki** [comment]
This should no longer be needed, the handlebars package should now be used for these extensions since scoring ties now favor installed packages vs. bundled packages.

See https://github.com/atom/atom/pull/6847 for more details, closing this out.

**Pull request closed without merging**
